// src/ui/components/checkbox.tsx
import clsx from 'clsx/lite'

interface Props {
  label: string
  id: string
  checked: boolean
  onChange: (checked: boolean) => void
}

export default function Checkbox({ label, id, checked, onChange }: Props) {
  return (
    <div className="flex items-center gap-4 sm:gap-6">
      <input
        className={clsx(
          'm-[2px] size-4 appearance-none border border-transparent ring-2',
          'shadow-green-200 transition-shadow checked:bg-green-200',
          'checked:not-active:ring-green-200 hover:shadow-lg',
          'active:not-checked:ring-green-200'
        )}
        type="checkbox"
        id={id}
        checked={checked}
        onChange={(event) => onChange(event.target.checked)}
      />
      <label htmlFor={id}>{label}</label>
    </div>
  )
}

// src/lib/checkbox.svelte
<script>
  /** @type {string} */
  export let name

  /** @type {string} */
  export let label

  /** @type {boolean} */
  export let checked
</script>

<label class="w-fit flex items-center gap-x-5 leading-none sm:gap-x-6">
  <input
    class="appearance-none h-5 w-5 border-2 bg-no-repeat bg-center
      transition-colors checked:(bg-primary border-primary)"
    type="checkbox"
    {name}
    bind:checked
  />
  <span class="sm:text-4.5">{label}</span>
</label>

<style>
  input:checked {
    background-image: url(/icons/check.svg);
  }
</style>
